In [1]:
include("representaciones.jl")

using RE

In [8]:
representacion(3,8)

8x8 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [2]:
protoBloque(3,1)

demas = [[0.5773502691896258,0.5773502691896258,0.5773502691896258],[0.8164965809277261,-0.4082482904638631,-0.4082482904638631],[-0.4082482904638631,0.8164965809277261,-0.4082482904638631]]


3x3 Array{Float64,2}:
 1.0   0.0   0.0
 0.0   1.0  -0.5
 0.0  -0.5   1.0

In [ ]:
function protoBloque(dim, rep)
    nuevaBase = ortogonal(dim)
    resultado = aplicacionTotal(nuevaBase)
    representacion = [x[rep] for x in resultado]
    matriz(nuevaBase, representacion)
end

In [3]:
?zeros

search: zeros spzeros nonzeros count_zeros set_zero_subnormals



```
zeros(type, dims)
```

Create an array of all zeros of specified type. The type defaults to Float64 if not specified.

```
zeros(A)
```

Create an array of all zeros with the same element type and shape as `A`.


In [4]:
zeros(Float64,3,3)

3x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [7]:
function matvec(dim)
    res = zeros(Float64,dim,dim)
    vector = ones(dim)
    for i in 1:dim
        res[1,i] = vector[i]/norm(vector)
    end
    for i in 2:dim # dim -1
        vector = -vector
        vector[i] = dim - 1
        for j in 1:dim
            res[i,j] = vector[j]/norm(vector)
        end
        vector = ones(dim)
    end
    res
end

matvec (generic function with 1 method)

In [8]:
matvec(3)

3x3 Array{Float64,2}:
  0.57735    0.57735    0.57735 
 -0.408248   0.816497  -0.408248
 -0.408248  -0.408248   0.816497

In [9]:
inv(matvec(3))*representacion(1,3)*matvec(3)

3x3 Array{Float64,2}:
  1.0          5.55112e-17  1.11022e-16
 -1.51082e-17  1.0          3.02164e-17
  0.0          5.55112e-17  1.0        