In [1]:
include("representaciones.jl")

RE

In [2]:
using RE

In [8]:
representacion(3,8)

8x8 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [9]:
representacion(7,8)*ones(8)

8-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [18]:
vector = ones(4)

4-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0

In [10]:
normalize(x) = x./sqrt(sumabs2(x, length(x)))

normalize (generic function with 1 method)

In [13]:
function ortogonal(dim)
    vector = ones(dim)
    demas = Array{Float64,1}[vector]
        for i in 1:dim - 1 # dim -1
        vector = -vector
        vector[i] = dim - 1
        push!(demas, vector)
        vector = ones(dim)
    end
    demas
end

ortogonal (generic function with 1 method)

In [14]:
ortogonal(3)

3-element Array{Array{Float64,1},1}:
 [1.0,1.0,1.0]  
 [2.0,-1.0,-1.0]
 [-1.0,2.0,-1.0]

In [15]:
valores = unos(3)

3-element Array{Array{Float64,1},1}:
 [1.0,1.0,1.0]  
 [2.0,-1.0,-1.0]
 [-1.0,2.0,-1.0]

In [30]:
representacion(1,3)*valores[1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [31]:
representacion(2,3)*valores[1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [32]:
representacion(3,3)*valores[1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [33]:
representacion(4,3)*valores[1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [34]:
representacion(5,3)*valores[1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [35]:
representacion(6,3)*valores[1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [16]:
function aplicarRepre(vector)
    dim =  length(vector)
    resultados = Array{Float64,1}[]
    for i in 1:factorial(dim)
        push!(resultados,representacion(i,dim)*vector)
    end
    resultados
end

aplicarRepre (generic function with 1 method)

In [17]:
function aplicacionTotal(base)
    map(aplicarRepre,base)
end

aplicacionTotal (generic function with 1 method)

In [19]:
valores = ortogonal(3)

3-element Array{Array{Float64,1},1}:
 [1.0,1.0,1.0]  
 [2.0,-1.0,-1.0]
 [-1.0,2.0,-1.0]

In [42]:
dot([1.0,1.0,1.0],[2.0,-1.0,-1.0])

0.0

In [43]:
dot([1.0,1.0,1.0],[-1.0,2.0,-1.0])

0.0

In [44]:
dot([-1.0,2.0,-1.0],[2.0,-1.0,-1.0])

-3.0

In [20]:
aplicacionTotal(valores)

3-element Array{Array{Array{Float64,1},1},1}:
 [[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0]]            
 [[2.0,-1.0,-1.0],[2.0,-1.0,-1.0],[-1.0,2.0,-1.0],[-1.0,-1.0,2.0],[-1.0,2.0,-1.0],[-1.0,-1.0,2.0]]
 [[-1.0,2.0,-1.0],[-1.0,-1.0,2.0],[2.0,-1.0,-1.0],[2.0,-1.0,-1.0],[-1.0,-1.0,2.0],[-1.0,2.0,-1.0]]

In [30]:
function salidaRepre(salida, rep)
    [x[rep] for x in salida]
end

salidaRepre (generic function with 1 method)

In [33]:
function protoBloque(dim, rep)
    nuevaBase = ortogonal(dim)
    resultado = aplicacionTotal(nuevaBase)
    representacion = [x[rep] for x in resultado]
    matriz(nuevaBase, representacion)
end

protoBloque (generic function with 1 method)

In [36]:
protoBloque(3,1)

3x3 Array{Float64,2}:
 3.0   0.0   0.0
 0.0   6.0  -3.0
 0.0  -3.0   6.0

In [37]:
protoBloque(3,2)

3x3 Array{Float64,2}:
 3.0   0.0   0.0
 0.0   6.0  -3.0
 0.0  -3.0  -3.0

In [38]:
protoBloque(3,3)

3x3 Array{Float64,2}:
 3.0   0.0   0.0
 0.0  -3.0   6.0
 0.0   6.0  -3.0

In [39]:
protoBloque(3,4)

3x3 Array{Float64,2}:
 3.0   0.0   0.0
 0.0  -3.0   6.0
 0.0  -3.0  -3.0

In [40]:
protoBloque(3,5)

3x3 Array{Float64,2}:
 3.0   0.0   0.0
 0.0  -3.0  -3.0
 0.0   6.0  -3.0

In [41]:
protoBloque(3,6)

3x3 Array{Float64,2}:
 3.0   0.0   0.0
 0.0  -3.0  -3.0
 0.0  -3.0   6.0

In [25]:
juanita = aplicacionTotal(valores)

3-element Array{Array{Array{Float64,1},1},1}:
 [[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0]]            
 [[2.0,-1.0,-1.0],[2.0,-1.0,-1.0],[-1.0,2.0,-1.0],[-1.0,-1.0,2.0],[-1.0,2.0,-1.0],[-1.0,-1.0,2.0]]
 [[-1.0,2.0,-1.0],[-1.0,-1.0,2.0],[2.0,-1.0,-1.0],[2.0,-1.0,-1.0],[-1.0,-1.0,2.0],[-1.0,2.0,-1.0]]

In [31]:
salidaRepre(juanita, 2)

3-element Array{Array{Float64,1},1}:
 [1.0,1.0,1.0]  
 [2.0,-1.0,-1.0]
 [-1.0,-1.0,2.0]

In [32]:
matriz(valores,ans)

3x3 Array{Float64,2}:
 3.0   0.0   0.0
 0.0   6.0  -3.0
 0.0  -3.0  -3.0

In [23]:
salidaRepre(aplicacionTotal(valores),2)

LoadError: LoadError: BoundsError
while loading In[23], in expression starting on line 1

In [21]:
aplicarRepre(valores[1])

6-element Array{Array{Float64,1},1}:
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]

In [37]:
aplicarRepre(valores[1])

6-element Array{Array{Float64,1},1}:
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]

In [38]:
aplicarRepre(valores[2])

6-element Array{Array{Float64,1},1}:
 [2.0,-1.0,-1.0]
 [2.0,-1.0,-1.0]
 [-1.0,2.0,-1.0]
 [-1.0,-1.0,2.0]
 [-1.0,2.0,-1.0]
 [-1.0,-1.0,2.0]

In [39]:
aplicarRepre(valores[3])

6-element Array{Array{Float64,1},1}:
 [-1.0,2.0,-1.0]
 [-1.0,-1.0,2.0]
 [2.0,-1.0,-1.0]
 [2.0,-1.0,-1.0]
 [-1.0,-1.0,2.0]
 [-1.0,2.0,-1.0]