In [1]:
include("representaciones.jl")

RE

In [2]:
using RE

In [3]:
representacion(7,8)

8x8 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [6]:
representacion(7,8)*ones(8)

8-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [18]:
vector = ones(4)

4-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0

In [21]:
normalize(x) = x./sqrt(sumabs2(x, length(x)))

normalize (generic function with 2 methods)

In [23]:
demas = Array{Float64,1}[vector]
for i in 1:3 # dim -1
    vector = -vector
    vector[i] = 4 - 1
    push!(demas, vector)
    vector = ones(4)
end
demas

4-element Array{Array{Float64,1},1}:
 [1.0,1.0,1.0,1.0]   
 [3.0,-1.0,-1.0,-1.0]
 [-1.0,3.0,-1.0,-1.0]
 [-1.0,-1.0,3.0,-1.0]

In [26]:
function unos(dim)
    vector = ones(dim)
    demas = Array{Float64,1}[vector]
        for i in 1:dim - 1 # dim -1
        vector = -vector
        vector[i] = dim - 1
        push!(demas, vector)
        vector = ones(dim)
    end
    demas
end

unos (generic function with 1 method)

In [27]:
unos(3)

3-element Array{Array{Float64,1},1}:
 [1.0,1.0,1.0]  
 [2.0,-1.0,-1.0]
 [-1.0,2.0,-1.0]

In [28]:
valores = unos(3)

3-element Array{Array{Float64,1},1}:
 [1.0,1.0,1.0]  
 [2.0,-1.0,-1.0]
 [-1.0,2.0,-1.0]

In [30]:
representacion(1,3)*valores[1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [31]:
representacion(2,3)*valores[1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [32]:
representacion(3,3)*valores[1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [33]:
representacion(4,3)*valores[1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [34]:
representacion(5,3)*valores[1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [35]:
representacion(6,3)*valores[1]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [36]:
function aplicarRepre(vector)
    dim =  length(vector)
    resultados = Array{Float64,1}[]
    for i in 1:factorial(dim)
        push!(resultados,representacion(i,dim)*vector)
    end
    resultados
end

aplicarRepre (generic function with 1 method)

In [41]:
function aplicacionTotal(base)
    map(aplicarRepre,base)
end

aplicacionTotal (generic function with 1 method)

In [42]:
aplicacionTotal(valores)

3-element Array{Array{Array{Float64,1},1},1}:
 [[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0]]            
 [[2.0,-1.0,-1.0],[2.0,-1.0,-1.0],[-1.0,2.0,-1.0],[-1.0,-1.0,2.0],[-1.0,2.0,-1.0],[-1.0,-1.0,2.0]]
 [[-1.0,2.0,-1.0],[-1.0,-1.0,2.0],[2.0,-1.0,-1.0],[2.0,-1.0,-1.0],[-1.0,-1.0,2.0],[-1.0,2.0,-1.0]]

In [37]:
aplicarRepre(valores[1])

6-element Array{Array{Float64,1},1}:
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]
 [1.0,1.0,1.0]

In [38]:
aplicarRepre(valores[2])

6-element Array{Array{Float64,1},1}:
 [2.0,-1.0,-1.0]
 [2.0,-1.0,-1.0]
 [-1.0,2.0,-1.0]
 [-1.0,-1.0,2.0]
 [-1.0,2.0,-1.0]
 [-1.0,-1.0,2.0]

In [39]:
aplicarRepre(valores[3])

6-element Array{Array{Float64,1},1}:
 [-1.0,2.0,-1.0]
 [-1.0,-1.0,2.0]
 [2.0,-1.0,-1.0]
 [2.0,-1.0,-1.0]
 [-1.0,-1.0,2.0]
 [-1.0,2.0,-1.0]