In [1]:
include("representaciones.jl")

using RE

In [9]:
type Permutacion
    perm :: Array{Int64,1}
    num :: Int64
end

In [10]:
ejemploTonto = Permutacion([1,2,3],1)

Permutacion([1,2,3],1)

In [12]:
typeof(ejemploTonto)

Permutacion

In [11]:
ejemploTonto.perm

3-element Array{Int64,1}:
 1
 2
 3

In [13]:
function generarPerm(rango)
    valores = collect(permutations(rango))
    sostén = Permutacion[]
    for i in 1:length(valores)
        push!(sostén, Permutacion(valores[i],i))
    end
    sostén
end

generarPerm (generic function with 1 method)

In [16]:
collect(permutations(1:3))

6-element Array{Array{Int64,1},1}:
 [1,2,3]
 [1,3,2]
 [2,1,3]
 [2,3,1]
 [3,1,2]
 [3,2,1]

In [22]:
original = generarPerm(1:3)

6-element Array{Permutacion,1}:
 Permutacion([1,2,3],1)
 Permutacion([1,3,2],2)
 Permutacion([2,1,3],3)
 Permutacion([2,3,1],4)
 Permutacion([3,1,2],5)
 Permutacion([3,2,1],6)

In [19]:
reservoir = map(generarPerm,collect(permutations(1:3)))

6-element Array{Array{Permutacion,1},1}:
 [Permutacion([1,2,3],1),Permutacion([1,3,2],2),Permutacion([2,1,3],3),Permutacion([2,3,1],4),Permutacion([3,1,2],5),Permutacion([3,2,1],6)]
 [Permutacion([1,3,2],1),Permutacion([1,2,3],2),Permutacion([3,1,2],3),Permutacion([3,2,1],4),Permutacion([2,1,3],5),Permutacion([2,3,1],6)]
 [Permutacion([2,1,3],1),Permutacion([2,3,1],2),Permutacion([1,2,3],3),Permutacion([1,3,2],4),Permutacion([3,2,1],5),Permutacion([3,1,2],6)]
 [Permutacion([2,3,1],1),Permutacion([2,1,3],2),Permutacion([3,2,1],3),Permutacion([3,1,2],4),Permutacion([1,2,3],5),Permutacion([1,3,2],6)]
 [Permutacion([3,1,2],1),Permutacion([3,2,1],2),Permutacion([1,3,2],3),Permutacion([1,2,3],4),Permutacion([2,3,1],5),Permutacion([2,1,3],6)]
 [Permutacion([3,2,1],1),Permutacion([3,1,2],2),Permutacion([2,3,1],3),Permutacion([2,1,3],4),Permutacion([1,3,2],5),Permutacion([1,2,3],6)]

In [20]:
reservoir[1]

6-element Array{Permutacion,1}:
 Permutacion([1,2,3],1)
 Permutacion([1,3,2],2)
 Permutacion([2,1,3],3)
 Permutacion([2,3,1],4)
 Permutacion([3,1,2],5)
 Permutacion([3,2,1],6)

In [37]:
elemento = 2
punto = 3
for juas in original
    if reservoir[elemento][punto].perm == juas.perm
        println("allright", reservoir[elemento][punto].num, juas.num)
    end
end

allright35


In [38]:
matricita = zeros(6,6)

6x6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [44]:
elemento = 1
punto = 6
for juas in original
    if reservoir[elemento][punto].perm == juas.perm
        matricita[reservoir[elemento][punto].num, juas.num] = 1
    end
end
matricita

6x6 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0

In [53]:
matricita = zeros(6,6)

6x6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [59]:
elemento = 3
matricita = zeros(6,6)
for i in 1:6
for juas in original
        if reservoir[elemento][i].perm == juas.perm
            matricita[reservoir[elemento][i].num, juas.num] = 1
    end
end
end
matricita

6x6 Array{Float64,2}:
 0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  1.0  0.0

In [64]:
function regular(n)
    matrices = Array{Float64,2}[]
    for i in 1:factorial(n)
        push!(matrices,unoRegular(i,n))
    end
    matrices
end

regular (generic function with 1 method)

In [65]:
regular(3)

6-element Array{Array{Float64,2},1}:
 6x6 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0
 6x6 Array{Float64,2}:
 0.0  1.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0
 6x6 Array{Float64,2}:
 0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  1.0  0.0
 6x6 Array{Float64,2}:
 0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  1.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 6x6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0
 0.0  1.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.

In [60]:
function unoRegular(elemento, n)
    original = generarPerm(1:n)
    matricita = zeros(factorial(n), factorial(n))
    reservoir = map(generarPerm,collect(permutations(1:n)))
    for i in 1:factorial(n)
        for juas in original
            if reservoir[elemento][i].perm == juas.perm
                matricita[reservoir[elemento][i].num, juas.num] = 1
            end
        end
    end
    matricita
end

unoRegular (generic function with 1 method)

In [63]:
unoRegular(3,3)

6x6 Array{Float64,2}:
 0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  1.0  0.0

In [17]:
generarPerm([2,1,3])

6-element Array{Permutacion,1}:
 Permutacion([2,1,3],1)
 Permutacion([2,3,1],2)
 Permutacion([1,2,3],3)
 Permutacion([1,3,2],4)
 Permutacion([3,2,1],5)
 Permutacion([3,1,2],6)

In [14]:
generarPerm(1:3)

6-element Array{Permutacion,1}:
 Permutacion([1,2,3],1)
 Permutacion([1,3,2],2)
 Permutacion([2,1,3],3)
 Permutacion([2,3,1],4)
 Permutacion([3,1,2],5)
 Permutacion([3,2,1],6)

In [3]:
collect(permutations(1:3))

6-element Array{Array{Int64,1},1}:
 [1,2,3]
 [1,3,2]
 [2,1,3]
 [2,3,1]
 [3,1,2]
 [3,2,1]

In [8]:
typeof([2,1,3])

Array{Int64,1}

In [5]:
collect(permutations([1,2,3]))

6-element Array{Array{Int64,1},1}:
 [1,2,3]
 [1,3,2]
 [2,1,3]
 [2,3,1]
 [3,1,2]
 [3,2,1]

In [6]:
function comparador(perm1, perm2)
    permutaciones = collect(permutations(perm1))
    for i in permutaciones
        if i == perm2
            return i
        end
    end
end

comparador (generic function with 1 method)

In [7]:
comparador([1,2,3],[3,1,2])

3-element Array{Int64,1}:
 3
 1
 2

In [4]:
map(x->collect(permutations(x)),ans)

6-element Array{Array{Array{Int64,1},1},1}:
 [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]
 [[1,3,2],[1,2,3],[3,1,2],[3,2,1],[2,1,3],[2,3,1]]
 [[2,1,3],[2,3,1],[1,2,3],[1,3,2],[3,2,1],[3,1,2]]
 [[2,3,1],[2,1,3],[3,2,1],[3,1,2],[1,2,3],[1,3,2]]
 [[3,1,2],[3,2,1],[1,3,2],[1,2,3],[2,3,1],[2,1,3]]
 [[3,2,1],[3,1,2],[2,3,1],[2,1,3],[1,3,2],[1,2,3]]

In [8]:
representacion(3,8)

8x8 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [2]:
protoBloque(3,1)

demas = [[0.5773502691896258,0.5773502691896258,0.5773502691896258],[0.8164965809277261,-0.4082482904638631,-0.4082482904638631],[-0.4082482904638631,0.8164965809277261,-0.4082482904638631]]


3x3 Array{Float64,2}:
 1.0   0.0   0.0
 0.0   1.0  -0.5
 0.0  -0.5   1.0

In [ ]:
function protoBloque(dim, rep)
    nuevaBase = ortogonal(dim)
    resultado = aplicacionTotal(nuevaBase)
    representacion = [x[rep] for x in resultado]
    matriz(nuevaBase, representacion)
end

In [3]:
?zeros

search: zeros spzeros nonzeros count_zeros set_zero_subnormals



```
zeros(type, dims)
```

Create an array of all zeros of specified type. The type defaults to Float64 if not specified.

```
zeros(A)
```

Create an array of all zeros with the same element type and shape as `A`.


In [4]:
zeros(Float64,3,3)

3x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [7]:
function matvec(dim)
    res = zeros(Float64,dim,dim)
    vector = ones(dim)
    for i in 1:dim
        res[1,i] = vector[i]/norm(vector)
    end
    for i in 2:dim # dim -1
        vector = -vector
        vector[i] = dim - 1
        for j in 1:dim
            res[i,j] = vector[j]/norm(vector)
        end
        vector = ones(dim)
    end
    res
end

matvec (generic function with 1 method)

In [8]:
matvec(3)

3x3 Array{Float64,2}:
  0.57735    0.57735    0.57735 
 -0.408248   0.816497  -0.408248
 -0.408248  -0.408248   0.816497

In [9]:
inv(matvec(3))*representacion(1,3)*matvec(3)

3x3 Array{Float64,2}:
  1.0          5.55112e-17  1.11022e-16
 -1.51082e-17  1.0          3.02164e-17
  0.0          5.55112e-17  1.0        